//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.01 at 04:33:59 AM EET 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "com.arabie.personSchema", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.arabie.models;
